apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginxapp
  name: nginxapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginxapp
  type: LoadBalancer
status:
  loadBalancer: {}
